services:
  drupal:
    image: drupal:9.3.13
    ports: 
    - "80:80"
    container_name: drupal
    volumes:
      - /var/www/html/sites
      - /var/www/html/modules
      - /var/www/html/profiles
      - /var/www/html/themes

  postgres:
    image: postgres:14.3
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=msp
